
//详细信息
export const CARDLIST_REQUEST = 'CARDLIST_REQUEST';
export const CARDLIST_SUCCESS = 'CARDLIST_SUCCESS';
export const CARDLIST_FAILED = 'CARDLIST_FAILED';

//审批意见
export const APPROVAL_REQUEST = 'APPROVAL_REQUEST';
export const APPROVAL_SUCCESS = 'APPROVAL_SUCCESS';
export const APPROVAL_FAILED = 'APPROVAL_FAILED';

//下一步处理人，人员树
export const STAFF_REQUEST = 'STAFF_REQUEST';
export const STAFF_SUCCESS = 'STAFF_SUCCESS';
export const STAFF_FAILED = 'STAFF_FAILED';


//下一步任务
export const NEXTTASK_REQUEST = 'NEXTTASK_REQUEST';
export const NEXTTASK_SUCCESS = 'NEXTTASK_SUCCESS';
export const NEXTTASK_FAILED = 'NEXTTASK_FAILED';

//审批流程信息
export const STEP_REQUEST = 'STEP_REQUEST';
export const STEP_SUCCESS = 'STEP_SUCCESS';
export const STEP_FAILED = 'STEP_FAILED';

//流程下一步接口
export const NEXTSTEP_REQUEST = 'NEXTSTEP_REQUEST';
export const NEXTSTEP_SUCCESS = 'NEXTSTEP_SUCCESS';
export const NEXTSTEP_FAILED = 'NEXTSTEP_FAILED';

//获取depID
export const DEPID_REQUEST = 'DEPID_REQUEST';
export const DEPID_SUCCESS = 'DEPID_SUCCESS';
export const DEPID_FAILED = 'DEPID_FAILED';

//获取当前步骤状态值
export const TASKSTATE_REQUEST = 'TASKSTATE_REQUEST';
export const TASKSTATE_SUCCESS = 'TASKSTATE_SUCCESS';
export const TASKSTATE_FAILED = 'TASKSTATE_FAILED';


//获取下下步审核步骤
export const SECONDTASK_REQUEST = 'SECONDTASK_REQUEST';
export const SECONDTASK_SUCCESS = 'SECONDTASK_SUCCESS';
export const SECONDTASK_FAILED = 'SECONDTASK_FAILED';

//只选审核步骤是，获取指定的下一步处理人
export const NEXTPERSON_REQUEST = 'NEXTPERSON_REQUEST';
export const NEXTPERSON_SUCCESS = 'NEXTPERSON_SUCCESS';
export const NEXTPERSON_FAILED = 'NEXTPERSON_FAILED';

//下一步结果集（陈）
export const NEXTTHINGS_MAP_REQUEST = 'NEXTTHINGS_MAP_REQUEST';
export const NEXTTHINGS_MAP_SUCCESS = 'NEXTTHINGS_MAP_SUCCESS';
//人员选择器（陈）
export const DEPANDUSER_MAP_REQUEST = 'DEPANDUSER_MAP_REQUEST';
export const DEPANDUSER_MAP_SUCCESS = 'DEPANDUSER_MAP_SUCCESS';