
//领导活动
export const ACTIVITIES_REQUEST = 'ACTIVITIES_REQUEST';
export const ACTIVITIES_SUCCESS = 'ACTIVITIES_SUCCESS';
export const ACTIVITIES_NOFETCH = 'ACTIVITIES_NOFETCH';
//活动详情
export const ACTIVITIESDETAIL_REQUEST = 'ACTIVITIESDETAIL_REQUEST';
export const ACTIVITIESDETAIL_SUCCESS = 'ACTIVITIESDETAIL_SUCCESS';