//数据条数请求
export const LIBRARY_AMOUNT_REQUEST = 'LIBRARY_AMOUNT_REQUEST';
export const LIBRARY_AMOUNT_SUCCESS = 'LIBRARY_AMOUNT_SUCCESS';
export const LIBRARY_AMOUNT_FAILED = 'LIBRARY_AMOUNT_FAILED';