export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const HAS_NEW_VERSION = 'HAS_NEW_VERSION';
export const CANCEL_LOGIN = 'CANCEL_LOGIN';
export const MAIL_MSG_REQUEST = 'MAIL_MSG_REQUEST';
export const MAIL_MSG_SUCCESS = 'MAIL_MSG_SUCCESS';
export const MAIL_COUNT_SUCCESS = 'MAIL_COUNT_SUCCESS';
