
export const MATTERCHOOSE_REQUEST = 'MATTERCHOOSE_REQUEST';
export const MATTERCHOOSE_SUCCESS = 'MATTERCHOOSE_SUCCESS';
export const MATTERCHOOSE_FAILED = 'MATTERCHOOSE_FAILED';
export const MATTERCHOOSE_HASMORE='MATTERCHOOOSE_HASMORE';
export const MATTERCHOOSE_ISLOADING='MATTERCHOOOSE_ISLOADING';
export const MATTERCHOOSE_NOFETCH='MATTERCHOOOSE_NOFETCH';
export const MATTERCHOOSE_COUNT='MATTERCHOOSE_COUNT';