
//会议安排
export const MEETINGARRANGE_REQUEST = 'MEETINGARRANGE_REQUEST';
export const MEETINGARRANGE_SUCCESS = 'MEETINGARRANGE_SUCCESS';
export const MEETINGARRANGE_NOFETCH = 'MEETINGARRANGE_NOFETCH';
export const MEETINGARRANGE_ISLOADING = 'MEETINGARRANGE_ISLOADING';
export const MEETINGARRANGE_HASMORE = 'MEETINGARRANGE_HASMORE';
//会议详情
export const MEETINGDETAIL_REQUEST = 'MEETINGDETAIL_REQUEST';
export const MEETINGDETAIL_SUCCESS = 'MEETINGDETAIL_SUCCESS';
export const MEETINGDETAIL_FAILED = 'MEETINGDETAIL_FAILED';