
export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS';
export const TRANSACTION_FAILED = 'TRANSACTION_FAILED';

export const USEREMAIL_REQUEST = 'USEREMAIL_REQUEST';
export const USEREMAIL_SUCCESS = 'USEREMAIL_SUCCESS';
export const USEREMAIL_FAILED = 'USEREMAIL_FAILED';

export const EMAILINFO_REQUEST = 'EMAILINFO_REQUEST';
export const EMAILINFO_SUCCESS = 'EMAILINFO_SUCCESS';
export const EMAILINFO_FAILED = 'EMAILINFO_FAILED';
